### ISSUE TITLE
Support strings for 'period' and 'timeout'

### ISSUE THREAD

**Issue by martinb3** [rackspace-cookbooks/rackspace_monitoring#12]
We should allow String arguments for these, as we have no intention of doing arithmetic on them (for all intents and purposes, they are strings for the sake of chef).

**Comment by jujugrrr** [comment]
I usually set number as a Fixnum even if I'm not planning to do arithmetic, as it's clearer which value is expected.  But indeed it would make sense to have them being string, however, it would mean we would have to do some checks to be sure we don't configure a yaml with "blabla" rather than 60.

The rackspace_monitoring_agent is expecting integer => http://docs.rackspace.com/cm/api/v1.0/cm-devguide/content/service-checks.html . So it might be nice to match types.

**Comment by martinb3** [comment]
> So it might be nice to match types.

Sounds good. We can worry about that in the rackspace_monitoring cookbook.

**Comment by martinb3** [comment]
I think there's going to be some issues with YAML (since a bare string doesn't need to be quoted, and even a quoted string might be made into an int in some YAML parsers) and strings that starts with numbers will break many YAML parsers as well. It feels like it would be better to let the agent check it's type requirements and have us just pass through the value.

**Comment by jujugrrr** [comment]
> It feels like it would be better to let the agent check it's type requirements and have us just pass through the value

There is no easy way to know if the agent is happy with the Yaml though, except if we start to really create checks and call the Rackspace API to validate it's been created properly. The better test we have for now is this https://github.com/rackspace-cookbooks/rackspace_monitoring/blob/master/test/integration/default/serverspec/default_spec.rb#L34-L36.

I feel only allowing Fixnum make sure that you end up with an integer which is more likely to work with the agent.

**Comment by martinb3** [comment]
@mburns What do you think we should do here? Type check arguments in Chef or let the Agent handle it? Does the Agent's YAML parser treat these the same way:

```
timeout: 30
timeout: "30"
timeout: "30a"
```

Thanks!

**Comment by rphillips** [comment]
The agent does not parse the yaml, but sends it to the monitoring service.

timeout: 30 would get parsed as an integer
timeout: "30" and "30a" would be parsed as a string

**Comment by martinb3** [comment]
So it sounds like that's an argument _for_ type checking in chef?

**Comment by rphillips** [comment]
I would agree. Chef might need to do this.

**Comment by martinb3** [comment]
I've submitted a PR that ensures the eventual content of the file is an integer where appropriate. Please review/consider. I did not do a conversion function as ruby's `to_i` does not seem to raise a problem when badly-formed strings are given, it simply converts them to the closest integer. We could do a conversion function if we wanted to also do something else, e.g. warn the user.

I know this may seem like a dirty change, but I think from the user's perspective, you pass a String like "1234" and it should _just work_ in Chef when you know the agent will accept it already.

**Comment by jujugrrr** [comment]
@marcoamorales There was a discussion about this, I would not have merged the PR until we finished to talk, especially when people who are part of the "argument" are offline. It's not like if it was an urgent change.

> I did not do a conversion function as ruby's to_i does not seem to raise a problem when badly-formed strings are given, it simply converts them to the closest integer

With the new PR if I've set a period to "bla60" it will silently change it to 0, making all my test and converge work.

Let's not support multiple type, and force the consumer to use an INT when the API documentation says it should be an INT. I think we too often try to handle all the possible cases, and I don't see the value here in supporting string and fixnum

**Comment by jujugrrr** [comment]
ps : I'm not a big fan of adding this kind of `to_i` in the template, I would have done it before to pass the variable to the template 

I'd rather do it there => https://github.com/rackspace-cookbooks/rackspace_monitoring/blob/master/libraries/helpers.rb#L154-L155

**Comment by niven01** [comment]
I've merged the revert https://github.com/rackspace-cookbooks/rackspace_monitoring/pull/14

I'm not sure I follow the logic of allowing a string to be entered when an INT is the desired type

**Comment by martinb3** [comment]
My problem with not allowing Strings but allowing Numbers is just that it puts barriers in front of a knowledgeable user, who might pass "1234" knowing that's a legal value in the agent. I would prefer the Chef code to stay out of my way if I know what I'm doing, vs. having the Chef code narrow the allowed values.

> ps : I'm not a big fan of adding this kind of to_i in the template, I would have done it before to pass the variable to the template
> 
> I'd rather do it there => https://github.com/rackspace-cookbooks/rackspace_monitoring/blob/master/libraries/helpers.rb#L154-L155

To be honest, I didn't see that logic. I would have probably done it there too.

**Comment by martinb3** [comment]
I'll let it die, since there is not consensus. But I feel that forcing numbers is not a [delightful experience](http://devops.com/2014/04/17/delivering-delight-chefconf-2014/), in the Chef community sense; at least it wouldn't be for me.
