### ISSUE TITLE
Duplicate entity issues when bootstrapping a node

### ISSUE THREAD

**Issue by martinb3** [rackspace-cookbooks/rackspace_monitoring#16]
Moved from https://github.com/rackspace-cookbooks/rackspace_cloudmonitoring/issues/22.

> From what I've gathered on this, the problem was introduced when our internal automation began creating MaaS entities for any server created at RAX. What appears to be happening is that sometimes the cookbook is run before internal automation has had a chance to create the entity. While the entity will eventually be created, if this cookbook is run prior, it will create the entity if it doesn't exist yet:
> 
> https://github.com/rackspace-cookbooks/rackspace_cloudmonitoring/blob/master/libraries/entity_hwrp.rb#L143
> 
> What this is causing is that chef creates an entity; then our internal automation creates another. The monitoring set up via the cookbook then sets up all checks on it's own entity and will result in false alerts when the server is deleted as there is nothing I can see that cleans these entities up.
> 
> IMHO we should not be creating entities at all if our internal automation is going to do so for any newly created server at RAX. We should wait for the entity to exist and then attach monitoring to it.

**Comment by mburns** [comment]
The cookbook as-is doesn't create entities, but will, when #20 lands.

I think the correct solution is to disable automation tools creating the entity when the agent can handle the logic itself, along with configuring the appropriate checks. Otherwise, we can have a flag that only optionally creates entities.

**Comment by dgivens** [comment]
Casual, uninterested third party here... The automation handles not only creating entities for new servers, but also _cleaning up_ entities when a server is destroyed. I suppose the automation could be changed to only try to clean up on deletion, but either way, it's a change that would have to be done by the ServerMill team.

**Comment by martinb3** [comment]
> I think the correct solution is to disable automation tools creating the entity when the agent can handle the logic itself

This feels like it's all an effort to workaround automation that isn't creating entities before making the server available. If we start disabling automation on servers, or define additional flags to handle these cases, it would potentially be a huge change in what our support staff expects (how to tell what servers are self-entity-create vs. automation-entity-create) vs. just fixing the automation to be consistent.

**Comment by mburns** [comment]
closing as solved/outdated.
