### ISSUE TITLE
Errors when using plugin_cookbook attribute

### ISSUE THREAD

**Issue by kylenas** [rackspace-cookbooks/rackspace_monitoring#41]
I'm having issues specifically when I try and utilize the plugin_cookbook attribute. If I add a monitoring check similar to this:

```
rackspace_monitoring_check 'MailTest' do
  type 'agent.plugin'
  plugin_cookbook 'rackspace_monitoring'
  plugin_filename 'MailTest.sh'
  alarm false
  action :create
end
```

I get this error:

```
NoMethodError: undefined method `parsed_plugin_filename' for Chef::Resource::RackspaceMonitoringCheck
```

if I remove the plugin_cookbook attribute chef will complete the run but the file doesn't get moved to /usr/lib/rackspace-monitoring-agent/plugins.

Everything works great if I use the plugin_url attribute, but I would rather keep everything in one place if possible. 

Any help would be great Thanks!

**Comment by martinb3** [comment]
Hello! `plugin_cookbook 'rackspace_monitoring'` is intended to be used to pass a template for a check in from another cookbook. You should be using `plugin_cookbook 'your_cookbook'` to use that attribute -- and it's specifically incompatible with `plugin_filename`.

Where is the `MailTest.sh` file that you want to copy to `/usr/lib/rackspace-monitoring-agent`? If it's at a URL, use `plugin_url` and `plugin_filename`. If it's in your own chef cookbook, use `plugin_cookbook` and your cookbook.

**Comment by kylenas** [comment]
Thanks for the quick reply! 

I think I understand where I went wrong. I think for our use case using plugin_url makes the most sense, 

Thank you for the help.
